version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: Data_Base
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPass # You Can Change That ... Create Your Own Password For More Secure 
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  petclinic:
    image: spring-petclinic
    container_name: App
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    ports:
      - "8080:8080"

volumes:
  mysql_data:


spring.profiles.active=postgres

spring.profiles.active=mysql