services:
  spring:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydb
      - SPRING_PROFILES_ACTIVE=mysql
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  mysql:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  postgres:
    deploy:
      replicas: 0 
        
