#SPDX-License-Identifier: MIT-0
---
- name: Restart docker
  service:
    name: docker
    state: restarted

- name: Restart nginx
  service:
    name: nginx
    state: restarted

# handlers file for theRole
