name: Java CI – Spring Petclinic

on:
  push:
    branches: [ master ]
    paths:
      - 'Task_10_actions/**'

env:
  APP_PATH: ./Task_10_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # # ✅ Only run tests
      # - name: Run unit tests
      #   working-directory: ${{ env.APP_PATH }}
      #   run: mvn -B test

  docker:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build the image from the Dockerfile
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_PATH }}
          file: ${{ env.APP_PATH }}/Dockerfile
          push: true            
          tags: bbodda123/petclinic:latest

      # 4. (Optional) Run docker-compose for integration tests
      - name: Start services with docker-compose
        working-directory: ${{ env.APP_PATH }}
        run: |
          docker compose up -d
          # wait for the app to be healthy, e.g.:
          sleep 30
          curl -f http://localhost:8090 || (docker-compose logs && exit 1)
          docker-compose down


# To Run The Jar File
# java -jar spring-petclinic-jar/spring-petclinic-3.5.0-SNAPSHOT.jar 