name: Java CI – Spring Petclinic

on:
  push:
    branches: [ master ]
    paths:
      - 'Task_10_actions/**'

env:
  APP_PATH: ./Task_10_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java and make caching for maven for later builds to make it faster
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3. Build, run tests, and install
      - name: Build and test with Maven
        working-directory: ${{ env.APP_PATH }}
        run: mvn clean install -B
        # 'install' will run tests and put the packaged app in your local Maven repo (~/.m2)

      # 4. (Optional) Upload the JAR artifact so you can download it from the workflow
      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic-jar
          path: ${{ env.APP_PATH }}/target/*.jar
